import { test } from 'node:test';
import assert from 'node:assert/strict';
import { writeFileSync, readFileSync, symlinkSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { Lifecycle, assessSecurity } from '../dist/index.js';
import { fixture, approved, oneTask, demoSpec, passingQa, git } from './lifecycle-helpers.mjs';
const noQa = { workflow: { qaLanes: [], maxQaRepairs: 0, maxActiveMs: 60000 } };

function withSecurity(spec, request, projectType='unknown') {
  const ctx=assessSecurity({text:request,projectType,files:[]});
  if (!ctx.topics.length) return spec;
  if (!spec.acceptance.some(x=>x.id==='AC-SEC')) spec.acceptance.push({id:'AC-SEC',description:'The security-sensitive behavior preserves the routed trust-boundary requirements.',verification:'Inspect implementation and observed negative security tests.'});
  if (!spec.tasks[0].acceptanceIds.includes('AC-SEC')) spec.tasks[0].acceptanceIds.push('AC-SEC');
  spec.minimumLane=ctx.minimumLane;
  spec.security={profile:{...ctx.profile},owaspTopics:ctx.topics.map(t=>t.id),threatModel:{required:ctx.requiresThreatModel,summary:ctx.requiresThreatModel?'Fixture threat model for the routed security surface.':'',assets:ctx.requiresThreatModel?['protected application state']:[],trustBoundaries:ctx.requiresThreatModel?['untrusted client -> application']:[],threats:ctx.requiresThreatModel?[{id:'TM-FIXTURE',category:'spoofing',description:'An untrusted actor attempts to cross the protected boundary.',mitigations:['Enforce the approved authentication/authorization and validation requirements.'],acceptanceIds:['AC-SEC']}]:[],assumptions:[]},requirements:[{id:'SEC-FIXTURE',title:'Apply controller-routed security requirements',owaspTopics:ctx.topics.map(t=>t.id),acceptanceIds:['AC-SEC'],verification:'Inspect code and runner evidence for the routed topics.',negativeTests:ctx.negativeTestsRequired?['Reject invalid or unauthorized input without changing protected state.']:[]}],assumptions:[],deferred:[]};
  return spec;
}
test('unapproved spec cannot start an agent', async (t) => { const f = fixture(t); const d = await f.life.draft({ repo: f.repo, config: f.config, request: 'Prepare multiplication.', proposal: demoSpec() }); await assert.rejects(f.life.run(d.id), /approval/i); assert.equal(f.life.pipeline.store.list().length, 0); });
test('open questions and wrong hash prevent Product approval', async (t) => { const f = fixture(t); const d = await f.life.draft({ repo: f.repo, config: f.config, request: 'Prepare multiplication.', proposal: demoSpec(true) }); await assert.rejects(f.life.approveSpec(d.id, 'bad', 'Test Owner', 'Explicit fixture approval.'), /hash/); await assert.rejects(f.life.approveSpec(d.id, d.data.contentHash, 'Test Owner', 'Explicit fixture approval.'), /questions/); });
test('refinement invalidates approval and changes revision hash', async (t) => { const f = fixture(t); let d = await approved(f); const old = d.data.contentHash; d = await f.life.refine(d.id, 'Clarify the same approved boundaries.', demoSpec()); assert.equal(d.data.approval, null); assert.equal(d.data.revision, 2); assert.notEqual(d.data.contentHash, old); await assert.rejects(f.life.run(d.id), /approval/i); await assert.rejects(f.life.approveSpec(d.id, old, 'Test Owner', 'Explicit fixture approval.'), /hash/); });
test('frontend UI work produces a reviewable mockup that is bound to spec approval before implementation', async (t) => { const f = fixture(t, { skills: { enabled: ['ui-design'], projectType: 'frontend', maxContextBytes: 16000 } }); const s = oneTask(); s.title = 'Arithmetic dashboard'; s.problem = 'The frontend needs a clear arithmetic dashboard before implementation begins.'; s.scope = ['Design and implement the arithmetic dashboard.']; s.tasks[0] = { ...s.tasks[0], title: 'Implement dashboard UI', description: 'Implement the approved arithmetic screen.', allowedPaths: ['src/math.mjs'] }; s.experience = { uiImpact: 'major', surfaces: ['Arithmetic dashboard'], rationale: 'The task changes the primary user-facing screen.' }; withSecurity(s, 'Create a distinctive arithmetic dashboard.', 'frontend'); let d = await f.life.draft({ repo: f.repo, config: f.config, request: 'Create a distinctive arithmetic dashboard.', proposal: s }); assert.ok(d.data.design); const designRoleEvent = f.life.store.documentEvents(d.id).filter(e => e.type === 'role.started' && e.data?.role === 'product').at(-1); assert.ok(designRoleEvent?.data?.guidance?.skills?.some(x => x.id === 'ui-design')); assert.ok(existsSync(d.data.design.indexPath)); assert.ok(d.data.design.screenPaths.every(existsSync)); const preview = readFileSync(d.data.design.screenPaths[0], 'utf8'); assert.match(preview, /Content-Security-Policy/); assert.doesNotMatch(preview, /<script/i); const bundleHash = f.life.summary(d).hash; assert.notEqual(bundleHash, d.data.contentHash); await assert.rejects(f.life.approveSpec(d.id, d.data.contentHash, 'Test Owner', 'Reviewed only the spec but not the design bundle.'), /hash/i); d = await f.life.approveSpec(d.id, bundleHash, 'Test Owner', 'Reviewed the specification and visual mockup together.'); assert.equal(d.data.status, 'approved'); });
test('single-task lifecycle creates one integrated human-review checkpoint and no intermediate review', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review'); assert.equal(d.data.attempts.length, 1); assert.notEqual(d.data.finalRunId, d.data.attempts[0].runId); assert.equal(d.data.validationRunIds.length, 1); assert.equal(f.life.pipeline.store.get(d.data.attempts[0].runId).task.reviewRequired, false); assert.equal(f.life.pipeline.store.get(d.data.finalRunId).task.reviewRequired, true); assert.equal(f.life.store.documentEvents(d.id).some(e => e.type === 'integration.reused'), false); });
test('whole spec performs QA repair, aggregate checks and local delivery', async (t) => { const f = fixture(t); const base = git(f.repo, 'rev-parse', 'HEAD'); let d = await approved(f); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review', JSON.stringify(d.data.error)); assert.ok(d.data.review); assert.ok(existsSync(d.data.review.candidateDirectory)); assert.ok(existsSync(d.data.review.reviewPath)); assert.ok(readFileSync(d.data.review.reviewPath, 'utf8').includes('Open this directory in your editor')); assert.equal(d.data.qaRepairs, 1); assert.equal(d.data.qa.report.verdict, 'pass'); assert.equal(d.data.validationRunIds.length, 2); assert.equal(d.data.completedTaskIds.length, 2); await assert.rejects(f.life.deliver(d.id, join(f.root, 'too-early')), /ready/i); d = await f.life.review(d.id, d.data.currentSha, 'Test Reviewer', 'Inspected integrated code and full criteria.'); assert.equal(d.data.status, 'ready'); d = await f.life.deliver(d.id, join(f.root, 'delivery')); assert.equal(d.data.status, 'delivered'); git(f.repo, 'apply', '--check', join(f.root, 'delivery/candidate.patch')); assert.equal(git(f.repo, 'rev-parse', 'HEAD'), base); assert.equal(git(f.repo, 'status', '--porcelain'), ''); assert.ok(readFileSync(join(f.root, 'delivery/run-events.jsonl'), 'utf8').includes('gate.finished')); });
test('high-risk assurance requires two distinct reviewers', async (t) => { const f = fixture(t, noQa); const s = oneTask(); s.minimumLane = 'high'; let d = await approved(f, s); d = await f.life.run(d.id); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer One', 'Inspected fixture changes and criteria.'); assert.equal(d.data.status, 'awaiting_review'); await assert.rejects(f.life.review(d.id, d.data.currentSha, 'reviewer one', 'Second claim by the same reviewer.'), /twice/); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer Two', 'Independent fixture inspection of changes.'); assert.equal(d.data.status, 'ready'); });
test('solo mode needs only one human approval even for high-risk integrated work', async (t) => { const f = fixture(t, { ...noQa, workflow: { ...noQa.workflow, reviewMode: 'solo' } }); const s = oneTask(); s.minimumLane = 'high'; let d = await approved(f, s); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review'); assert.equal(f.life.pipeline.store.get(d.data.finalRunId).risk.lane, 'high'); d = await f.life.review(d.id, d.data.currentSha, 'Solo Owner', 'Reviewed the exact integrated high-risk candidate.'); assert.equal(d.data.status, 'ready'); });

test('new companion files inside the approved module flow without a scope approval', async (t) => { const f = fixture(t, noQa); const s = oneTask(); s.tasks[0] = { ...s.tasks[0], id: 'COMPANION', title: 'Add companion helper', description: 'Extend math and add a supporting helper in the same source module.', allowedPaths: ['src/math.mjs'] }; let d = await approved(f, s); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review', JSON.stringify(d.data.error)); assert.equal(d.data.scopeAmendments.length, 0); const taskRun = f.life.pipeline.store.get(d.data.attempts[0].runId); assert.ok(taskRun.changeSet.added.includes('src/helper.mjs')); assert.ok(f.life.pipeline.store.events(taskRun.id).some(e => e.type === 'scope.auto_expanded')); });
test('manual QA remains mandatory even when low-level run was approved', async (t) => { const f = fixture(t); let d = await approved(f, oneTask()); d = await f.life.run(d.id, { manualQa: true }); assert.equal(d.data.error.code, 'QA_REQUIRED'); const final = f.life.pipeline.store.get(d.data.finalRunId); await f.life.pipeline.approve(final.id, final.candidateSha, 'Low-level reviewer', 'Fixture attempts approval before QA.'); await assert.rejects(f.life.deliver(d.id, join(f.root, 'bad')), /QA/); d = await f.life.importQa(d.id, passingQa(d)); assert.equal(f.life.pipeline.store.get(final.id).approvals.length, 0); d = await f.life.run(d.id, { manualQa: true }); assert.equal(d.data.status, 'awaiting_review'); });
test('QA repair budget stops recurring requests', async (t) => { const f = fixture(t, { workflow: { qaLanes: ['standard', 'high'], maxQaRepairs: 0, maxActiveMs: 60000 } }); let d = await approved(f); d = await f.life.run(d.id); assert.equal(d.data.error.code, 'QA_REJECTED'); assert.equal(d.data.qaRepairs, 0); assert.equal(d.data.attempts.length, 2); });
test('revalidation invalidates QA and human approvals', async (t) => { const f = fixture(t); let d = await approved(f); d = await f.life.run(d.id); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer Test', 'Inspected integrated fixture changes.'); const active = d.data.activeMs; d = await f.life.verify(d.id); assert.equal(d.data.qa, null); assert.equal(f.life.pipeline.store.get(d.data.finalRunId).approvals.length, 0); assert.ok(d.data.activeMs > active); await assert.rejects(f.life.deliver(d.id, join(f.root, 'bad')), /QA/); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review'); });
test('running an already paused spec does not recall Product or Implementer', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); const count = f.life.store.events(d.data.finalRunId).filter(e => e.type === 'agent.started').length; d = await f.life.run(d.id); assert.equal(d.data.attempts.length, 1); assert.equal(f.life.store.events(d.data.finalRunId).filter(e => e.type === 'agent.started').length, count); });
test('spec cannot be rewritten after the first attempt', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); await assert.rejects(f.life.refine(d.id, 'Change criteria after coding.', oneTask()), /follow-up/); });
test('structural scope expansion retains the candidate and can be amended without returning to the old base', async (t) => { const f = fixture(t, noQa); const s = oneTask(); s.tasks[0] = { ...s.tasks[0], id: 'OUTSIDE', title: 'Create structural helper', description: 'Modify math and create a helper outside the approved module.', allowedPaths: ['src/math.mjs'] }; let d = await approved(f, s); d = await f.life.run(d.id); assert.equal(d.data.status, 'blocked'); assert.equal(d.data.error.code, 'SCOPE_AMENDMENT_REQUIRED'); assert.equal(d.data.scopeAmendments.length, 1); const amendment = d.data.scopeAmendments[0]; const failed = f.life.pipeline.store.get(amendment.sourceRunId); assert.ok(failed.candidateSha); d = await f.life.approveScopeAmendment(d.id, amendment.id, 'Test Owner', 'Approve the explicit structural helper path for this retained candidate.'); assert.equal(d.data.activeRunId !== null, true); d = await f.life.run(d.id); assert.equal(d.data.status, 'awaiting_review'); assert.equal(d.data.currentSha, failed.candidateSha); assert.ok(d.data.completedTaskIds.includes('OUTSIDE')); });
test('stale spec cannot start against a moved local base', async (t) => { const f = fixture(t, noQa); const d = await approved(f, oneTask()); writeFileSync(join(f.repo, 'README.md'), 'New baseline\n'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'base moved'); await assert.rejects(f.life.run(d.id), /HEAD/); assert.equal(f.life.pipeline.store.list().length, 0); });
test('spec survives closing and reopening the SQLite store', async (t) => { const f = fixture(t, noQa); const d = await approved(f, oneTask()); f.life.close(); const other = new Lifecycle(f.state); t.after(() => other.close()); assert.equal(other.get(d.id).data.contentHash, d.data.contentHash); const result = await other.run(d.id); assert.equal(result.data.status, 'awaiting_review'); });
test('changed delivery files are detected on repeat export', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer Test', 'Inspected integrated fixture changes.'); const path = join(f.root, 'delivery'); await f.life.deliver(d.id, path); writeFileSync(join(path, 'candidate.patch'), 'tampered'); await assert.rejects(f.life.deliver(d.id, path), /changed/); });
test('existing branch at a different commit is never overwritten', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer Test', 'Inspected integrated fixture changes.'); git(f.repo, 'branch', 'feature/taken'); await assert.rejects(f.life.branch(d.id, 'feature/taken', true), /another commit/); await assert.rejects(f.life.branch(d.id, 'feature/new', false), /confirmation/); });
test('local close refuses a base that does not contain the candidate', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); d = await f.life.review(d.id, d.data.currentSha, 'Reviewer Test', 'Inspected integrated fixture changes.'); d = await f.life.deliver(d.id, join(f.root, 'delivery')); const target = git(f.repo, 'symbolic-ref', '--short', 'HEAD'); await assert.rejects(f.life.closeLocal(d.id, target, d.data.baseSha, 'Integrator Test', 'Observed expected local integration.'), /git merge-base/); assert.equal(f.life.get(d.id).data.status, 'delivered'); });
test('rejected spec can never export or publish a candidate', async (t) => { const f = fixture(t, noQa); let d = await approved(f, oneTask()); d = await f.life.run(d.id); f.life.reject(d.id, 'The requirement needs a new explicit decision.'); await assert.rejects(f.life.deliver(d.id, join(f.root, 'bad')), /rejected/); await assert.rejects(f.life.publicationCandidate(d.id), /published/); });
test('active-time budget exhaustion cannot yield ready', async (t) => { const f = fixture(t, noQa); const d = await approved(f, oneTask()); d.data.activeMs = d.data.config.workflow.maxActiveMs; f.life.store.saveDocument(d, 'test.exhaust'); await assert.rejects(f.life.run(d.id), /budget/); assert.equal(f.life.pipeline.store.list().length, 0); });
test('delivery rejects an external symlink ancestor into the source before writing', async (t) => {
    const f = fixture(t, noQa);
    let d = await approved(f, oneTask());
    d = await f.life.run(d.id);
    d = await f.life.review(d.id, d.data.currentSha, 'Reviewer', 'Reviewed the exact candidate.');
    const link = join(f.root, 'source-alias');
    symlinkSync(f.repo, link, 'dir');
    await assert.rejects(f.life.deliver(d.id, join(link, 'not-created', 'delivery')), /redirects/i);
    assert.equal(existsSync(join(f.repo, 'not-created')), false);
});

test('Product loads the committed Decision Ledger and refuses to silently drop confirmed business decisions', async (t) => {
  const f = fixture(t);
  const ledger = { schemaVersion: 1, decisions: [{ id:'D-AUTH', subject:'Authentication', value:'email/password', enforcement:'product', status:'confirmed', source:'operator', sourceQuote:'email/password', rationale:'Explicit operator decision.', supersedes:[] }] };
  mkdirSync(join(f.repo,'.agent-pipeline'),{recursive:true});
  writeFileSync(join(f.repo,'.agent-pipeline/DECISIONS.json'),JSON.stringify(ledger,null,2)+'\n');
  git(f.repo,'add','.'); git(f.repo,'commit','-qm','add authoritative decisions');
  const without = withSecurity(oneTask(), 'Implement login with email/password. Authentication: email/password');
  await assert.rejects(() => f.life.draft({ repo:f.repo, config:f.config, request:'Implement login with email/password.', proposal:without }), /D-AUTH|decision/i);
  const withCoverage = withSecurity(oneTask(), 'Implement login with email/password. Authentication: email/password');
  withCoverage.decisionCoverage = [{ decisionId:'D-AUTH', acceptanceIds:[withCoverage.acceptance[0].id], rationale:'The covered acceptance criterion is used as the fixture proxy for the confirmed auth decision.' }];
  const doc = await f.life.draft({ repo:f.repo, config:f.config, request:'Implement login with email/password.', proposal:withCoverage });
  assert.equal(doc.data.decisionLedger.decisions[0].id,'D-AUTH');
  assert.equal(doc.data.content.decisionCoverage[0].decisionId,'D-AUTH');
});

test('invalid committed Decision Ledger is never silently treated as empty', async (t) => {
  const f = fixture(t);
  mkdirSync(join(f.repo,'.agent-pipeline'),{recursive:true});
  writeFileSync(join(f.repo,'.agent-pipeline/DECISIONS.json'),'{"schemaVersion":1,"decisions":[{"id":"D1"}]}\n');
  git(f.repo,'add','.'); git(f.repo,'commit','-qm','add invalid decision ledger');
  await assert.rejects(() => f.life.draft({ repo:f.repo, config:f.config, request:'Prepare multiplication.', proposal:oneTask() }), /schema|decision/i);
});
