import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync, mkdirSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { inspectProject, proposeConfiguration, planInstallation, applyInstallation, doctor } from '../dist/lifecycle/onboarding.js';
import { fixture, git } from './lifecycle-helpers.mjs';
test('onboarding detects real npm scripts without executing them', async (t) => { const f = fixture(t); const inv = await inspectProject(f.repo); assert.equal(inv.stack, 'node-javascript'); assert.equal(inv.packageManager, 'npm'); const p = proposeConfiguration(inv); assert.equal(p.questions.length, 0); assert.deepEqual(p.config.setup[0].command, ['npm', 'ci', '--ignore-scripts']); assert.deepEqual(p.config.gates.find(g => g.id === 'test').command, ['npm', 'run', 'test']); assert.equal(git(f.repo, 'status', '--porcelain'), ''); });
test('SvelteKit is detected as frontend and check is promoted to a real gate', async (t) => { const f = fixture(t); const pkg = JSON.parse(readFileSync(join(f.repo, 'package.json'), 'utf8')); pkg.devDependencies = { '@sveltejs/kit': '2.0.0', svelte: '5.0.0' }; pkg.scripts.check = 'svelte-check --tsconfig ./tsconfig.json'; writeFileSync(join(f.repo, 'package.json'), JSON.stringify(pkg, null, 2) + '\n'); writeFileSync(join(f.repo, 'svelte.config.js'), 'export default {};\n'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'svelte fixture'); const inv = await inspectProject(f.repo); assert.equal(inv.stack, 'sveltekit-typescript'); assert.equal(inv.projectType, 'frontend'); const proposal = proposeConfiguration(inv); assert.equal(proposal.config.skills.projectType, 'frontend'); assert.deepEqual(proposal.config.gates.find(g => g.id === 'check').command, ['npm', 'run', 'check']); });

test('review mode is chosen once in onboarding instead of editing pipeline JSON manually', async (t) => { const f = fixture(t); const p = await planInstallation(f.life.store, f.repo, { config: f.config, reviewMode: 'solo' }); assert.equal(p.data.config.workflow.reviewMode, 'solo'); });
test('placeholder test is never promoted to a valid gate', async (t) => { const f = fixture(t); const inv = await inspectProject(f.repo); inv.scripts.test = 'echo "Error: no test specified" && exit 1'; const p = proposeConfiguration(inv); assert.ok(p.questions.length > 0); assert.equal(p.config.gates.some(g => g.id === 'test'), false); });
test('unknown stack stays blocked instead of inventing checks', () => { const p = proposeConfiguration({ repo: '/r', baseSha: 'a'.repeat(40), stack: 'unknown', files: [], scripts: {}, packageManager: null, warnings: [] }); assert.ok(p.questions.length > 0); });
test('conflicting manifests produce an explicit unresolved question', async (t) => { const f = fixture(t); writeFileSync(join(f.repo, 'pnpm-lock.yaml'), 'lockfileVersion: 9\n'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'conflicting managers'); assert.ok(proposeConfiguration(await inspectProject(f.repo)).questions.length > 0); });
test('installation requires exact hash and preserves existing AGENTS content', async (t) => { const f = fixture(t); const p = await planInstallation(f.life.store, f.repo, { config: f.config }); await assert.rejects(applyInstallation(f.life.store, p.id, 'a'.repeat(64), 'Test Owner', 'Reviewed fixture installation.'), /hash/i); assert.equal(existsSync(join(f.repo, 'pipeline.v2.json')), false); const applied = await applyInstallation(f.life.store, p.id, p.data.hash, 'Test Owner', 'Reviewed fixture installation.', true); assert.equal(applied.data.applied, true); assert.ok(applied.data.commitSha); assert.match(readFileSync(join(f.repo, 'AGENTS.md'), 'utf8'), /Do not erase this text/); assert.equal(git(f.repo, 'status', '--porcelain'), ''); assert.ok(existsSync(join(f.repo, '.agent-pipeline/ASSISTANT.md'))); });
test('installation refuses preexisting operator config', async (t) => { const f = fixture(t); writeFileSync(join(f.repo, 'pipeline.v2.json'), '{}'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'already configured'); await assert.rejects(planInstallation(f.life.store, f.repo, { config: f.config }), /overwrite/); });
test('installation rejects changed source between preview and approval', async (t) => { const f = fixture(t); const p = await planInstallation(f.life.store, f.repo, { config: f.config }); writeFileSync(join(f.repo, 'README.md'), 'Modified\n'); await assert.rejects(applyInstallation(f.life.store, p.id, p.data.hash, 'Test Owner', 'Reviewed fixture installation.'), /uncommitted/); });
test('unanswered onboarding proposal cannot apply', async (t) => { const f = fixture(t); const p = await planInstallation(f.life.store, f.repo, { config: f.config }); p.data.questions.push('An unresolved choice'); const { installHash } = await import('../dist/lifecycle/onboarding.js'); p.data.hash = installHash(p.data); f.life.store.saveDocument(p, 'test.changed'); await assert.rejects(applyInstallation(f.life.store, p.id, p.data.hash, 'Test Owner', 'Reviewed fixture installation.'), /questions/); });
test('installation rejects ignored symlink directory escape', async (t) => { const f = fixture(t); writeFileSync(join(f.repo, '.gitignore'), 'node_modules/\n.agent-pipeline\n'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'ignored path'); const p = await planInstallation(f.life.store, f.repo, { config: f.config }); const outside = join(f.root, 'outside'); mkdirSync(outside); symlinkSync(outside, join(f.repo, '.agent-pipeline')); await assert.rejects(applyInstallation(f.life.store, p.id, p.data.hash, 'Test Owner', 'Reviewed fixture installation.'), /symlink/); assert.equal(existsSync(join(outside, 'ASSISTANT.md')), false); });
test('assisted onboarding invokes a read-only role and accepts a structured proposal', async (t) => { const f = fixture(t); const p = await planInstallation(f.life.store, f.repo, { assist: true, agent: f.config.agent }); assert.equal(p.data.questions.length, 0); assert.ok(f.life.store.documentEvents(p.id).some(e => e.type === 'role.finished')); assert.equal(git(f.repo, 'status', '--porcelain'), ''); });
test('doctor does not run code without explicit execute flag', async (t) => { const f = fixture(t); const r = await doctor(f.life.pipeline, f.repo, f.config, false); assert.equal(r.passed, null); assert.equal(f.life.pipeline.store.list().length, 0); });
test('doctor executes real baseline checks without calling Implementer', async (t) => { const f = fixture(t, { agent: { type: 'command', command: ['NONEXISTENT-WORKER'] } }); const r = await doctor(f.life.pipeline, f.repo, f.config, true); assert.equal(r.passed, true); assert.ok(!f.life.pipeline.store.events(r.runId).some(e => e.type === 'agent.started')); });
test('doctor reports a failing baseline, never an implicit pass', async (t) => { const f = fixture(t); writeFileSync(join(f.repo, 'src/math.mjs'), 'export const add=(a,b)=>a-b;\n'); git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'introduce bug'); const r = await doctor(f.life.pipeline, f.repo, f.config, true); assert.equal(r.passed, false); });

test('onboarding promotes existing project-owned security scripts without inventing scanners', async (t) => {
  const f = fixture(t);
  const pkg = JSON.parse(readFileSync(join(f.repo, 'package.json'), 'utf8'));
  pkg.scripts['security:ci'] = 'node --test test/security.test.mjs';
  writeFileSync(join(f.repo, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
  writeFileSync(join(f.repo, 'test/security.test.mjs'), "import test from 'node:test';test('security fixture',()=>{});\n");
  git(f.repo, 'add', '.'); git(f.repo, 'commit', '-qm', 'security script fixture');
  const inv = await inspectProject(f.repo);
  assert.deepEqual(inv.securityScripts, ['security:ci']);
  const proposal = proposeConfiguration(inv);
  const gate = proposal.config.gates.find(g => g.id === 'security-security-ci');
  assert.deepEqual(gate.command, ['npm', 'run', 'security:ci']);
  assert.deepEqual(gate.lanes, ['standard','high']);
  assert.ok(!proposal.config.gates.some(g => g.command.join(' ').includes('npm audit')));
});
