import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { apv, decision } from './cli-helpers.mjs';
import { waive } from './support/rules.mjs';
import { decisionLedgerMarkdown } from '../dist/lifecycle/decisions.js';
import { mergeLedgers } from '../dist/stack/regenerate.js';

/**
 * Pipeline review of 3 October 2026, point b1: the batch as the normal way to merge. Generated files (the code map, the
 * decision ledger and its Markdown) in conflict between two pull requests are regenerated in the batch instead of leaving
 * a pull request out; before its merge, such a branch is updated with the same content as proven; `--dast` scans the head.
 */

const CLI = fileURLToPath(new URL('../dist/cli.js', import.meta.url));
const fakeGh = fileURLToPath(new URL('./support/fake-gh.mjs', import.meta.url));
chmodSync(fakeGh, 0o755);
const identity = { GIT_AUTHOR_NAME: 'Test', GIT_AUTHOR_EMAIL: 'test@localhost', GIT_COMMITTER_NAME: 'Test', GIT_COMMITTER_EMAIL: 'test@localhost' };
const git = (cwd, ...args) => execFileSync('git', ['-c', 'core.hooksPath=/dev/null', '-c', 'commit.gpgsign=false', ...args],
  { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, ...identity } }).trim();
const allow = { APV_ALLOW_MERGE: '1' };

/**
 * An origin and a clone whose checks are a suite and the code map (`apv map --check`, task stage), a shared module and a
 * decision ledger on main, with the map and the ledger Markdown generated by the tool. Pull requests, each with the map
 * regenerated in its commit (decision D1): #21 adds src/one.mjs, #22 adds src/two.mjs, #23 adds decision D-A, #24 adds
 * decision D-B, #25 changes the value of D-0, #26 changes it otherwise, #27 changes a.txt and #28 changes a.txt otherwise.
 */
async function lotProject(t, extraConfig = {}, { archmap = false } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'apv3-lot-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const origin = join(root, 'origin.git');
  execFileSync('git', ['init', '-q', '--bare', '-b', 'main', origin]);
  const repo = join(root, 'repo');
  git(root, 'clone', '-q', origin, repo);
  git(repo, 'switch', '-q', '-c', 'main');
  mkdirSync(join(repo, '.apv')); mkdirSync(join(repo, 'src'));
  writeFileSync(join(repo, '.apv', 'config.json'), JSON.stringify({ gates: [
    { id: 'suite', stage: 'full', command: [process.execPath, '-e', 'process.exit(require("fs").existsSync("BAD") ? 1 : 0)'] },
    { id: 'code-map', stage: 'task', readOnly: true, command: [process.execPath, CLI, 'map', '--check'] }], ...extraConfig }));
  writeFileSync(join(repo, 'a.txt'), 'a\n');
  writeFileSync(join(repo, 'src', 'shared.mjs'), 'export const shared = 1;\n');
  const writeLedger = (dir, value) => { writeFileSync(join(dir, '.apv', 'DECISIONS.json'), `${JSON.stringify(value, null, 2)}\n`); writeFileSync(join(dir, '.apv', 'DECISIONS.md'), decisionLedgerMarkdown(value)); };
  writeLedger(repo, { schemaVersion: 1, decisions: [decision('D-0')] });
  if (archmap) assert.equal((await apv(repo, ['structure', 'map'])).code, 0, 'the architecture map written at the base');
  assert.equal((await apv(repo, ['map'])).code, 0);
  git(repo, 'add', '-A'); git(repo, 'commit', '-qm', 'base'); git(repo, 'push', '-q', 'origin', 'main');
  const prs = {};
  const branch = async (n, name, change, withMap = true) => {
    git(repo, 'switch', '-q', '-c', name, 'main');
    await change(repo);
    if (withMap) assert.equal((await apv(repo, ['map'])).code, 0, 'the implementer regenerates the map in his commit');
    git(repo, 'add', '-A'); git(repo, 'commit', '-qm', name); git(repo, 'push', '-q', 'origin', name);
    const sha = git(repo, 'rev-parse', 'HEAD');
    git(origin, 'update-ref', `refs/pull/${n}/head`, sha);
    waive(repo, sha, ['relecture', 'captures', 'controles', 'maquette']);
    prs[n] = { number: n, state: 'OPEN', isDraft: false, baseRefName: 'main', headRefName: name, headRefOid: sha, mergeable: 'MERGEABLE', mergeStateStatus: 'CLEAN',
      statusCheckRollup: [{ __typename: 'CheckRun', name: 'ci', status: 'COMPLETED', conclusion: 'SUCCESS' }] };
  };
  await branch(21, 'pr-one', r => writeFileSync(join(r, 'src', 'one.mjs'), "import { shared } from './shared.mjs';\nexport const one = shared + 1;\n"));
  await branch(22, 'pr-two', r => writeFileSync(join(r, 'src', 'two.mjs'), "import { shared } from './shared.mjs';\nexport const two = shared + 2;\n"));
  await branch(23, 'pr-da', r => writeLedger(r, { schemaVersion: 1, decisions: [decision('D-0'), decision('D-A')] }));
  await branch(24, 'pr-db', r => writeLedger(r, { schemaVersion: 1, decisions: [decision('D-0'), decision('D-B')] }));
  await branch(25, 'pr-d0-x', r => writeLedger(r, { schemaVersion: 1, decisions: [decision('D-0', { value: 'X' })] }));
  await branch(26, 'pr-d0-y', r => writeLedger(r, { schemaVersion: 1, decisions: [decision('D-0', { value: 'Y' })] }));
  await branch(27, 'pr-a-x', r => writeFileSync(join(r, 'a.txt'), 'x\n'));
  await branch(28, 'pr-a-y', r => writeFileSync(join(r, 'a.txt'), 'y\n'));
  git(repo, 'switch', '-q', 'main');
  const file = join(root, 'gh.json');
  writeFileSync(file, JSON.stringify({ prs, behavior: { liveHeads: [21, 22, 23, 24, 25, 26, 27, 28] }, calls: [], origin }));
  const env = { ...identity, APV_GH: fakeGh, FAKE_GH_STATE: file, APV_STACK_POLL_MS: '5', APV_STACK_POLL_ATTEMPTS: '3', APV_ALLOW_MERGE: '',
    APV_LOCK_DIR: join(root, 'locks'), APV_LOCK_POLL_MS: '20' };
  /** Adds a pull request later (the behavior of the fake gh is kept), from the branch `name`, with its map regenerated. */
  const more = async (n, name, change, behavior = {}, withMap = true) => {
    await branch(n, name, change, withMap);
    git(repo, 'switch', '-q', 'main');
    const state = JSON.parse(readFileSync(file, 'utf8'));
    state.prs[n] = prs[n]; state.behavior = { ...state.behavior, liveHeads: [...state.behavior.liveHeads, n], ...behavior };
    if (behavior.repo) state.repo = behavior.repo;
    writeFileSync(file, JSON.stringify(state));
  };
  return {
    root, origin, repo, env, prs, more,
    head: branch => git(origin, 'rev-parse', `refs/heads/${branch}`),
    run: (args, extra = {}) => apv(repo, ['stack', 'batch', ...args], { ...env, ...extra }),
    main: () => git(origin, 'rev-parse', 'refs/heads/main'),
    tree: ref => git(origin, 'rev-parse', `${ref}^{tree}`),
    show: (ref, path) => git(origin, 'show', `${ref}:${path}`),
    parents: ref => git(origin, 'rev-list', '--parents', '-n', '1', ref).split(/\s+/).slice(1),
    merges: () => JSON.parse(readFileSync(file, 'utf8')).calls.filter(c => c[1] === 'merge').map(c => Number(c[2])),
    log: () => existsSync(join(repo, '.apv/state/stack.log')) ? readFileSync(join(repo, '.apv/state/stack.log'), 'utf8').trim().split('\n').map(l => JSON.parse(l)) : [],
  };
}

test('batch: two pull requests that each regenerated the code map conflict on it; the batch regenerates it instead of leaving one out, the code-map check proves it', async t => {
  const p = await lotProject(t);
  const r = await p.run(['21', '22', '--json']);
  assert.equal(r.code, 0, r.stdout + r.stderr);
  const lot = r.json().proven;
  assert.deepEqual(lot.members.map(m => m.number), [21, 22]);
  assert.deepEqual(lot.excluded, []);
  assert.deepEqual(lot.members[0].regenerated, [], 'the first merge has nothing to regenerate');
  assert.ok(lot.members[1].regenerated.includes('.apv/code-map.md'), JSON.stringify(lot.members[1].regenerated));
  assert.match(lot.proof.summary, /2\/2 contrôle\(s\) réussi\(s\) ; apv gates verify à 0/);
  assert.match(r.stderr, /PR #22 : (conflit sur les seuls fichiers générés, régénérés dans la fusion|carte du code périmée par la fusion, régénérée dans la fusion) \(.*\.apv\/code-map\.md/);
  // The regenerated map describes both modules; one merge commit per pull request, nothing else.
  const map = git(p.repo, 'show', `${lot.head}:.apv/code-map.md`);
  assert.ok(map.includes('one.mjs') && map.includes('two.mjs'), map);
  assert.equal(git(p.repo, 'rev-list', '--first-parent', '--count', `${lot.base}..${lot.head}`), '2');
  assert.equal(git(p.repo, 'rev-list', '--merges', '--count', `${lot.base}..${lot.head}`), '2');
  const human = await p.run(['21', '22']);
  assert.match(human.stdout, /PR #22 : fichiers générés régénérés dans le lot : .*\.apv\/code-map\.md/);
});

test('batch --merge: a branch whose merge regenerated generated files is updated first (same tree as proven, two parents, pushed without force), journaled, then merged', async t => {
  const p = await lotProject(t);
  const before = p.prs[22].headRefOid;
  const r = await p.run(['21', '22', '--merge', '--json'], allow);
  assert.equal(r.code, 0, r.stdout + r.stderr);
  const report = r.json();
  assert.deepEqual(report.merged, [21, 22]);
  assert.deepEqual(p.merges(), [21, 22]);
  assert.equal(report.finalTree.identical, true);
  assert.equal(p.tree(p.main()), git(p.repo, 'rev-parse', `${report.proven.head}^{tree}`));
  assert.deepEqual(report.refreshed.map(x => [x.pr, x.branch, x.from, x.files.includes('.apv/code-map.md')]), [[22, 'pr-two', before, true]]);
  const refreshed = report.refreshed[0].to;
  // The update: the old head and the target after #21, the tree proven in the batch for #22; the branch was pushed with it.
  const targetAfter21 = p.log().find(e => e.event === 'batch-merge' && e.pr === 21).targetAfter;
  assert.deepEqual(p.parents(refreshed), [before, targetAfter21]);
  assert.equal(p.tree(refreshed), report.proven.members[1].tree);
  assert.equal(report.mergedHeads.find(m => m.pr === 22).head, refreshed, 'merged at the updated head');
  assert.deepEqual(p.log().map(e => [e.event, e.pr]), [['batch-merge', 21], ['batch-refresh', 22], ['batch-merge', 22]]);
  assert.equal(p.log()[1].files.includes('.apv/code-map.md'), true);
  assert.match(r.stderr, /PR #22 : fichiers générés régénérés dans le lot \(.*\.apv\/code-map\.md.*\) : mise à jour de pr-two sur main avant la fusion\./);
  assert.match(r.stderr, /Mise à jour de la PR #22 : (conflit sur les seuls fichiers générés|carte du code périmée par la fusion), régénérés? dans la fusion/);
  // The result on main: both modules in the map, the map up to date.
  const map = p.show('refs/heads/main', '.apv/code-map.md');
  assert.ok(map.includes('one.mjs') && map.includes('two.mjs'));
});

test('batch: the decision ledger in conflict is merged by the union of its decisions (its Markdown regenerated); the same decision changed on both sides, or a conflict of the code, still leaves the pull request out', async t => {
  const p = await lotProject(t);
  const r = await p.run(['23', '24', '--json']);
  assert.equal(r.code, 0, r.stdout + r.stderr);
  const lot = r.json().proven;
  assert.deepEqual(lot.members.map(m => m.number), [23, 24]);
  assert.deepEqual(lot.members[1].regenerated.sort(), ['.apv/DECISIONS.json', '.apv/DECISIONS.md']);
  const ledger = JSON.parse(git(p.repo, 'show', `${lot.head}:.apv/DECISIONS.json`));
  assert.deepEqual(ledger.decisions.map(d => d.id), ['D-0', 'D-A', 'D-B']);
  assert.equal(git(p.repo, 'show', `${lot.head}:.apv/DECISIONS.md`), decisionLedgerMarkdown(ledger).trim(), 'the Markdown is rendered from the merged ledger');
  // The other direction: D-0 changed on both sides is a real conflict; a.txt changed on both sides too.
  const conflict = await p.run(['25', '26', '--json']);
  assert.equal(conflict.code, 1);
  assert.deepEqual(conflict.json().left.map(l => l.pr), [26]);
  assert.match(conflict.json().left[0].reason, /\.apv\/DECISIONS\.json : décision D-0 modifiée des deux côtés/);
  const code = await p.run(['27', '28', '--json']);
  assert.equal(code.code, 1);
  assert.match(code.json().left[0].reason, /fichier\(s\) en conflit hors des fichiers générés : a\.txt/);
  assert.deepEqual(p.merges(), []);
});

test('mergeLedgers: symmetric union, changes on one side kept, deletions honoured, real conflicts refused', () => {
  const [d0, d1, d2, d3] = [decision('D-0'), decision('D-1'), decision('D-2'), decision('D-3')];
  const base = { schemaVersion: 1, decisions: [d0, d1, d2] };
  const ours = { schemaVersion: 1, decisions: [d0, { ...d1, value: 'changed' }, d2, d3] };
  const theirs = { schemaVersion: 1, decisions: [d0, d1, decision('D-A')] };
  const ab = mergeLedgers(base, ours, theirs); const ba = mergeLedgers(base, theirs, ours);
  assert.deepEqual(ab, ba, 'the same whichever side is ours');
  assert.deepEqual(ab.ledger.decisions.map(d => [d.id, d.value]), [['D-0', 'Value'], ['D-1', 'changed'], ['D-3', 'Value'], ['D-A', 'Value']]);
  assert.deepEqual(mergeLedgers(null, { schemaVersion: 1, decisions: [d1] }, { schemaVersion: 1, decisions: [d0] }).ledger.decisions.map(d => d.id), ['D-0', 'D-1'], 'both new: added, sorted');
  assert.deepEqual(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, { ...d1, value: 'x' }, d2] }, { schemaVersion: 1, decisions: [d0, { ...d1, value: 'y' }, d2] }), { conflict: 'décision D-1 modifiée des deux côtés' });
  assert.deepEqual(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d2] }, { schemaVersion: 1, decisions: [d0, { ...d1, value: 'y' }, d2] }), { conflict: "décision D-1 modifiée d'un côté et retirée de l'autre" });
  assert.deepEqual(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d1, d2, d3] }, { schemaVersion: 1, decisions: [d0, d1, d2, { ...d3, value: 'other' }] }), { conflict: 'décision D-3 ajoutée différemment des deux côtés' });
  // Replacements across the two sides: two added decisions that replace the same one, or a replacement of a decision retired on the other side.
  const over = (id, target) => decision(id, { supersedes: [target] });
  assert.deepEqual(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d1, d2, over('D-3', 'D-1')] }, { schemaVersion: 1, decisions: [d0, d1, d2, over('D-4', 'D-1')] }), { conflict: 'décisions D-3 et D-4, ajoutées de part et d\'autre, remplacent toutes deux D-1' });
  assert.deepEqual(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d1, d2, over('D-3', 'D-1')] }, { schemaVersion: 1, decisions: [d0, d2] }), { conflict: 'décision D-3 remplace D-1, absente du registre fusionné' });
  assert.ok('ledger' in mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d1, d2, over('D-3', 'D-1')] }, { schemaVersion: 1, decisions: [d0, d1, d2, over('D-4', 'D-2')] }), 'two replacements of two decisions: fine');
  assert.match(mergeLedgers(base, { schemaVersion: 1, decisions: [d0, d1, d2, decision('D-3', { status: 'ambiguous' })] }, base).conflict ?? '', /registre fusionné invalide/);
});

test('batch: a pull request whose merge leaves the generated files impossible to regenerate is left out, the batch returns to the tree before it, the next one enters', async t => {
  const p = await lotProject(t, {}, { archmap: true });
  const module = (name, k) => r => writeFileSync(join(r, 'src', `${name}.mjs`), `import { shared } from './shared.mjs';\nexport const ${name} = shared + ${k};\n`);
  // #35 duplicates a marker of the architecture map: apv map refuses it, nothing can be regenerated after its merge.
  await p.more(35, 'pr-marker', r => {
    const file = join(r, 'docs', 'carte-architecture.md');
    const text = readFileSync(file, 'utf8');
    writeFileSync(file, `${text}\n${/<!-- apv:[a-z]+:[a-z-]+ -->/.exec(text)[0]}\n<!-- /dup -->\n`);
  }, {}, false);
  await p.more(36, 'pr-three', module('three', 6));
  const r = await p.run(['21', '35', '36', '--json']);
  assert.equal(r.code, 1, r.stdout + r.stderr);
  const lot = r.json().proven;
  assert.deepEqual(lot.members.map(m => m.number), [21, 36]);
  assert.deepEqual(lot.excluded.map(x => x.pr), [35]);
  assert.match(lot.excluded[0].reason, /fichiers générés non régénérés après sa fusion \(le lot reste à l'arbre d'avant\)/);
  assert.doesNotMatch(lot.excluded[0].reason, /conflit avec les PR précédentes/);
  assert.match(r.stderr, /PR #35 sans fichiers générés régénérables après sa fusion, laissée hors du lot/);
  // Exactly two merges in the batch (#21, #36), #36 on top of #21's merge; nothing of #35 in the tree.
  assert.equal(git(p.repo, 'rev-list', '--first-parent', '--count', `${lot.base}..${lot.head}`), '2');
  assert.deepEqual(git(p.repo, 'rev-list', '--parents', '-n', '1', lot.members[1].mergeCommit).split(/\s+/).slice(1)[0], lot.members[0].mergeCommit);
  assert.throws(() => git(p.repo, 'merge-base', '--is-ancestor', p.prs[35].headRefOid, lot.head), 'the head of #35 is not in the batch');
  assert.doesNotMatch(git(p.repo, 'show', `${lot.head}:docs/carte-architecture.md`), /<!-- \/dup -->/);
  assert.equal(r.json().status, 'partiel');
  assert.match(lot.proof.summary, /2\/2 contrôle\(s\) réussi\(s\)/);
});

test('batch --dast: the dynamic scan the target declares runs on the proven head before any merge; a failed scan merges nothing; refused without review.dast', async t => {
  const scan = `const [dir] = process.argv.slice(1); require('fs').writeFileSync(require('path').join(dir, 'zap.html'), '<p>0</p>'); console.log('scan ' + process.env.APV_DAST_COMMIT); process.exit(Number(process.env.SCAN_EXIT ?? 0));`;
  const p = await lotProject(t, { review: { dast: { command: [process.execPath, '-e', scan, '{{reportDir}}'], passEnv: ['SCAN_EXIT'] } } });
  const r = await p.run(['21', '22', '--dast', '--json']);
  assert.equal(r.code, 0, r.stdout + r.stderr);
  const dast = r.json().proven.dast;
  assert.equal(dast.ok, true);
  assert.equal(dast.status, 'passed');
  assert.ok(existsSync(join(dast.reportDir, 'summary.json')) && existsSync(join(dast.reportDir, 'zap.html')), dast.reportDir);
  const summary = JSON.parse(readFileSync(join(dast.reportDir, 'summary.json'), 'utf8'));
  assert.equal(summary.commit, r.json().proven.head, 'the scan is of the head of the batch');
  assert.match(r.stderr, /scan dynamique de la tête [0-9a-f]{12} \(apv dast run sur le lot\)/);
  assert.match((await p.run(['21', '22', '--dast'])).stdout, /Scan dynamique du lot : terminé à 0 [\s\S]*Lot prouvé et scanné : APV_ALLOW_MERGE=1 apv stack batch <mêmes PR> --merge --dast/);
  // Failed scan: proven but stopped, nothing merged even with --merge.
  const failed = await p.run(['21', '22', '--dast', '--merge', '--json'], { ...allow, SCAN_EXIT: '1' });
  assert.equal(failed.code, 1, failed.stdout + failed.stderr);
  assert.equal(failed.json().status, 'arrêté');
  assert.match(failed.json().stopped.reasons[0], /scan dynamique du lot en échec \(scan dynamique en échec \(code 1\)/);
  assert.deepEqual(p.merges(), []);
  assert.deepEqual(failed.json().merged, []);
  // Without a declared scan: usage error, nothing built; --dast is for batch only.
  const bare = await lotProject(t);
  assert.equal((await bare.run(['21', '22', '--dast'])).code, 2);
  assert.equal((await apv(bare.repo, ['stack', 'plan', '21', '--dast'], bare.env)).code, 2);
});

test('batch --merge never pushes on a long-lived, protected or default branch: the update is refused, nothing pushed, nothing else merged', async t => {
  const p = await lotProject(t);
  const module = (name, k) => r => writeFileSync(join(r, 'src', `${name}.mjs`), `import { shared } from './shared.mjs';\nexport const ${name} = shared + ${k};\n`);
  // Each one adds a module, so its map conflicts with #21's once #21 is in the batch: an update would be needed.
  await p.more(31, 'develop', module('dev', 3));
  await p.more(32, 'prot/1', module('rel', 4), { protected: ['prot/1'] });
  await p.more(33, 'apv3', module('apv', 5), { repo: { default_branch: 'apv3' } });
  // #34 comes from an integration branch: neither default nor protected nor long-lived by name, but the base of open #37.
  await p.more(34, 'integration', module('integ', 7));
  await p.more(37, 'pr-on-integration', module('onit', 8));
  const state = JSON.parse(readFileSync(join(p.root, 'gh.json'), 'utf8'));
  state.prs[37].baseRefName = 'integration';
  writeFileSync(join(p.root, 'gh.json'), JSON.stringify(state));
  // A partner merged first (#21, then #22), then the target itself moved: each refused branch conflicts on the map.
  const cases = [[['21', '31'], 'develop', /est une branche de longue durée \(stack\.keepBranches : develop\)/], [['22', '32'], 'prot/1', /est protégée sur GitHub/], [['33'], 'apv3', /est la branche par défaut du dépôt sur GitHub \(apv3\)/], [['34'], 'integration', /est la base de la ou des PR ouverte\(s\) #37 \(branche d'intégration\)/]];
  for (const [prs, name, why] of cases) {
    const n = Number(prs[prs.length - 1]);
    const before = p.head(name);
    const r = await p.run([...prs, '--merge', '--json'], allow);
    assert.equal(r.code, 1, r.stdout + r.stderr);
    assert.equal(r.json().stopped.pr, n);
    assert.match(r.json().stopped.reasons[0], why);
    assert.match(r.json().stopped.reasons[0], /le lot ne pousse jamais sur une telle branche ; fusionner main dans la branche, apv map, pousser, relancer le lot/);
    assert.equal(p.head(name), before, `${name} untouched`);
    assert.ok(!r.json().refreshed.some(x => x.pr === n), `#${n} never updated (the partner may be)`);
    assert.ok(!r.json().merged.includes(n), `#${n} never merged`);
  }
  assert.deepEqual(p.merges(), [21, 22], 'the partners only');
  // The open pull requests of the branch unreadable: refused as well, never assumed free.
  const broken = JSON.parse(readFileSync(join(p.root, 'gh.json'), 'utf8'));
  broken.behavior.pullsFail = true;
  writeFileSync(join(p.root, 'gh.json'), JSON.stringify(broken));
  const unread = await p.run(['34', '--merge', '--json'], allow);
  assert.equal(unread.code, 1);
  assert.match(unread.json().stopped.reasons[0], /a des PR ouvertes qui ne se lisent pas \(gh api repos\/o\/r\/pulls\)/);
  broken.behavior.pullsFail = false;
  writeFileSync(join(p.root, 'gh.json'), JSON.stringify(broken));
  // The local default branch (origin/HEAD) refuses too, before any gh call.
  git(p.repo, 'symbolic-ref', 'refs/remotes/origin/HEAD', 'refs/remotes/origin/develop');
  const local = await p.run(['31', '--merge', '--json'], allow);
  assert.equal(local.code, 1);
  assert.match(local.json().stopped.reasons[0], /est la branche par défaut du dépôt \(origin\/HEAD\)/);
  assert.deepEqual(p.merges(), [21, 22]);
});

test('batch without --dast while the target declares review.dast: said in the report and in JSON (dastSkipped)', async t => {
  const scan = `const [dir] = process.argv.slice(1); require('fs').writeFileSync(require('path').join(dir, 'zap.html'), '<p>0</p>');`;
  const p = await lotProject(t, { review: { dast: { command: [process.execPath, '-e', scan, '{{reportDir}}'] } } });
  const r = await p.run(['21', '22', '--json']);
  assert.equal(r.code, 0, r.stdout + r.stderr);
  assert.equal(r.json().dastSkipped, true);
  const human = await p.run(['21', '22']);
  assert.match(human.stdout, /Scan dynamique non lancé \(--dast absent\) alors que la cible déclare review\.dast\./);
  const merged = await p.run(['21', '22', '--merge'], allow);
  assert.equal(merged.code, 0, merged.stdout + merged.stderr);
  assert.match(merged.stdout, /Scan dynamique non lancé \(--dast absent\) alors que la cible déclare review\.dast : PR fusionnées sans scan du lot ; le scan par PR \(apv dast run\) reste dû avant la fusion\./);
  assert.equal((await p.run(['21', '22', '--dast', '--json'])).json().dastSkipped, false);
  const bare = await lotProject(t);
  assert.equal((await bare.run(['21', '22', '--json'])).json().dastSkipped, false, 'nothing declared: nothing to say');
});
